// React-PureCSS/src/App.jsx
import { useState } from 'react'
import './App.css'

const todosInit = [
  {
    id: 324234,
    text: 'Uma tarefa',
    completed: false
  },
  {
    id: 365734,
    text: 'Outra tarefa',
    completed: false
  },
  {
    id: 658754,
    text: 'Uma tarefa feita',
    completed: true
  }
]

function App() {
  const [todos, setTodos] = useState([...todosInit])
  const [newTodoText, setNewTodoText] = useState('')

  function handleAddTodo(e) {
    e.preventDefault()

    if (!newTodoText) return

    const newTodo = {
      id: Date.now(),
      text: newTodoText,
      completed: false
    }
    setTodos([...todos, newTodo])
    setNewTodoText('')
  }

  return (
    <div className='container'>
      <h1>Todos</h1>

      <form onSubmit={handleAddTodo}>
        <input
          onChange={e => setNewTodoText(e.target.value)}
          type='text'
          placeholder="What's next?"
          value={newTodoText}
        />
        <button type='submit'>+</button>
      </form>

      <ul>
        {todos.map(todo => (
          <li
            className={`todo ${todo.completed ? 'completed' : ''}`}
            key={todo.id}
          >
            <input
              type='checkbox'
              checked={todo.completed}
              onChange={() =>
                setTodos(
                  todos.map(t => {
                    if (t.id === todo.id) t.completed = !t.completed
                    return t
                  })
                )
              }
            />
            <span>{todo.text}</span>
            <button
              onClick={() => setTodos(todos.filter(t => t.id != todo.id))}
            >
              Delete
            </button>
          </li>
        ))}
      </ul>
      <div className='footer'>
        <span>React JS</span>
      </div>
    </div>
  )
}

export default App

// VueJS-PureCSS/src/App.vue
<script setup>
import { ref } from 'vue'

const todosInit = [
  {
    id: 324234,
    text: 'Uma tarefa',
    completed: false
  },
  {
    id: 365734,
    text: 'Outra tarefa',
    completed: false
  },
  {
    id: 658754,
    text: 'Uma tarefa feita',
    completed: true
  }
]

const todos = ref([...todosInit])
const newTodo = ref('')

function onSubmit() {
  if (newTodo.value)
    todos.value.push({ id: Date.now(), text: newTodo.value, completed: false })

  newTodo.value = ''
}

function deleteTodo(id) {
  todos.value = todos.value.filter(todo => todo.id != id)
}
</script>

<template>
  <div class="container">
    <h1>Todos</h1>

    <form @submit.prevent="onSubmit">
      <input placeholder="What's next?" v-model="newTodo" />
      <button type="submit">+</button>
    </form>

    <ul v-if="todos.length">
      <li
        v-for="todo in todos"
        :key="todo.id"
        :class="{ completed: todo.completed }"
      >
        <input
          type="checkbox"
          @change="todo.completed = !todo.completed"
          :checked="todo.completed"
        />
        <span>{{ todo.text }} </span>
        <button @click="deleteTodo(todo.id)">Delete</button>
      </li>
    </ul>

    <div class="empty" v-else>Add some todos!</div>
    <div class="footer">
      <span>VueJS</span>
    </div>
  </div>
</template>

<style scoped></style>
