// Svelte/src/App.svelte
<script>
  import initialTodos from '../../shared/initTodos'
  let todos = [...initialTodos]
  let newTodo = ''

  function addTodo() {
    todos = [...todos, { id: Date.now(), text: newTodo, completed: false }]
  }

  function updateTodoStatus(id) {
    todos = todos.map(todo => {
      if (todo.id === id) todo.completed = !todo.completed
      return todo
    })
  }

  function deleteTodo(id) {
    todos = todos.filter(todo => todo.id !== id)
  }
</script>

<main>
  <div class="container">
    <h1>Tasks</h1>

    <form on:submit|preventDefault={addTodo}>
      <input bind:value={newTodo} type="text" placeholder="What's next?" />
      <button type="submit">+</button>
    </form>

    {#if todos.length}
      <ul>
        {#each todos as todo}
          <li class:completed={todo.completed}>
            <input
              type="checkbox"
              on:change={() => updateTodoStatus(todo.id)}
              bind:checked={todo.completed}
            />
            <span>
              {todo.text}
            </span>
            <button on:click={() => deleteTodo(todo.id)}>Delete</button>
          </li>
        {/each}
      </ul>
    {:else}
      <div class="empty">Add some tasks!</div>
    {/if}
    <footer>
      <span>Svelte</span>
    </footer>
  </div>
</main>

<style>
</style>

// VueJS/src/App.vue
<script setup>
import { ref } from 'vue'
import initialTodos from '../../shared/initTodos'

const todos = ref([...initialTodos])
const newTodo = ref('')

function onSubmit() {
  if (newTodo.value)
    todos.value.push({ id: Date.now(), text: newTodo.value, completed: false })

  newTodo.value = ''
}

function deleteTodo(id) {
  todos.value = todos.value.filter(todo => todo.id != id)
}
</script>

<template>
  <div class="container">
    <h1>Tasks</h1>

    <form @submit.prevent="onSubmit">
      <input placeholder="What's next?" v-model="newTodo" />
      <button type="submit">+</button>
    </form>

    <ul v-if="todos.length">
      <li
        v-for="todo in todos"
        :key="todo.id"
        :class="{ completed: todo.completed }"
      >
        <input
          type="checkbox"
          @change="todo.completed = !todo.completed"
          :checked="todo.completed"
        />
        <span>{{ todo.text }} </span>
        <button @click="deleteTodo(todo.id)">Delete</button>
      </li>
    </ul>

    <div class="empty" v-else>Add some todos!</div>
    <footer>
      <span>Vue</span>
    </footer>
  </div>
</template>

<style scoped></style>
