// React/src/App.jsx
import { useState } from 'react'
import './App.css'
import initialTodos from '../../shared/initTodos'

function App() {
  const [todos, setTodos] = useState([...initialTodos])
  const [newTodoText, setNewTodoText] = useState('')

  function handleAddTodo(e) {
    e.preventDefault()

    if (!newTodoText) return

    const newTodo = {
      id: Date.now(),
      text: newTodoText,
      completed: false
    }
    setTodos([...todos, newTodo])
    setNewTodoText('')
  }

  return (
    <div className='container'>
      <h1>Tasks</h1>

      <form onSubmit={handleAddTodo}>
        <input
          onChange={e => setNewTodoText(e.target.value)}
          type='text'
          placeholder="What's next?"
          value={newTodoText}
        />
        <button type='submit'>+</button>
      </form>

      {todos.length ? (
        <ul>
          {todos.map(todo => (
            <li
              className={`todo ${todo.completed ? 'completed' : ''}`}
              key={todo.id}
            >
              <input
                type='checkbox'
                checked={todo.completed}
                onChange={() =>
                  setTodos(
                    todos.map(t => {
                      if (t.id === todo.id) t.completed = !t.completed
                      return t
                    })
                  )
                }
              />
              <span>{todo.text}</span>
              <button
                onClick={() => setTodos(todos.filter(t => t.id != todo.id))}
              >
                Delete
              </button>
            </li>
          ))}
        </ul>
      ) : (
        <div class='empty'>Add some tasks!</div>
      )}
      <footer>
        <span>React</span>
      </footer>
    </div>
  )
}

export default App

// Solid/src/App.jsx
import { createSignal, For, Show } from 'solid-js'
import initialTodos from '../../shared/initTodos'

const [todos, setTodos] = createSignal([...initialTodos])
const [newTodoText, setNewTodoText] = createSignal('')

function App() {
  function updateTodoStatus(id) {
    setTodos(
      todos().map(todo =>
        todo.id == id ? { ...todo, completed: !todo.completed } : todo
      )
    )
  }

  function addTodo(e) {
    e.preventDefault()
    setTodos([
      ...todos(),
      { id: Date.now(), text: newTodoText(), completed: false }
    ])
    setNewTodoText('')
  }

  function deleteTodo(id) {
    setTodos(todos().filter(todo => todo.id != id))
  }

  return (
    <div class='container'>
      <h1>Tasks</h1>

      <form onSubmit={e => addTodo(e)}>
        <input
          value={newTodoText()}
          onInput={e => setNewTodoText(e.currentTarget.value)}
          type='text'
          placeholder="What's next?"
        />
        <button type='submit'>+</button>
      </form>

      <Show when={todos().length}>
        <ul>
          <For each={todos()}>
            {todo => (
              <li classList={{ completed: todo.completed }}>
                <input
                  type='checkbox'
                  checked={todo.completed}
                  onChange={() => updateTodoStatus(todo.id)}
                />
                <span>{todo.text}</span>
                <button onClick={() => deleteTodo(todo.id)}>Delete</button>
              </li>
            )}
          </For>
        </ul>
      </Show>
      <Show when={!todos().length}>
        <div class='empty'>Add some tasks!</div>
      </Show>
      <footer>
        <span>Solid</span>
      </footer>
    </div>
  )
}

export default App
